version: '3.7'

services:
  reth-rpc-node:
    env_file:
      - .bitcoin.env
    container_name: reth-rpc-node
    image: us-central1-docker.pkg.dev/botanix-391913/botanix-testnet-node-v1/botanix-poa-node
    command:
      - poa
      - --federation-config-path=/reth/botanix_testnet/config/chain.toml
      - --datadir=/reth/botanix_testnet/data
      - --http
      - --http.addr=0.0.0.0
      - --http.port=8545
      - --http.api=debug,eth,net,trace,txpool,web3,rpc
      - --http.corsdomain=*
      - --ws
      - --ws.port=8546
      - -vvv
      - --bitcoind.url=${BITCOIND_HOST}
      - --bitcoind.username=${BITCOIND_USER}
      - --bitcoind.password=${BITCOIND_PASS}
      - --btc-network=signet
      - --p2p-secret-key=/reth/botanix_testnet/config/discovery-secret
      - --port=30303
      - --metrics=0.0.0.0:9001
      - --abci-port=26658
      - --abci-host=0.0.0.0
      - --cometbft-rpc-port=26657
      - --cometbft-rpc-host=cometbft-consensus-node
      - --sync.enable_state_sync
      - --sync.enable_historical_sync
      - --is-testnet
    ports:
      - 8545:8545
      - 8546:8546
      - 9001:9001
      - 30303:30303
      - 26658:26658
    volumes:
      - ./config/reth:/reth/botanix_testnet/config:rw
      - ./data/reth:/reth/botanix_testnet/data:rw
    restart: unless-stopped
    networks:
      - rpc_net

  cometbft-consensus-node:
    container_name: cometbft-consensus-node
    image: cometbft/cometbft:v1.0.0 
    ports:
      - 26656:26656
      - 26657:26657
      - 26660:26660
    volumes:
      - ./config/cometbft:/cometbft/config:rw
      - ./data/cometbft:/cometbft/data:rw
    restart: unless-stopped
    user: root
    command: >
      node
      --home=/cometbft
      --proxy_app="reth-rpc-node:26658"
      --moniker="INPUT_YOUR_MONIKER_HERE"
      --key-type=secp256k1
      --p2p.persistent_peers=${PERSISTENT_PEERS_LIST:-}
      --p2p.laddr=${P2P_LADDR:-tcp://0.0.0.0:26656}
      --rpc.laddr=${RPC_LADDR:-tcp://0.0.0.0:26657}
    environment:
      - LOG_LEVEL=INFO
      - CHAIN_ID=3636
    networks:
      - rpc_net

networks:
  rpc_net:
    name: rpc_net
    driver: bridge
