version: "3.7"

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: "3"

services:
  mutiny-bitcoind:
    container_name: "mutiny-bitcoind"
    image: us-central1-docker.pkg.dev/botanix-391913/botanix-mutinynet-bitcoind/botanix-mutinynet-bitcoind:v1
    user: "0:1000"
    logging: *default-logging
    restart: always
    stop_grace_period: 1m
    volumes:
      - ./config/bitcoind/.bitcoin:/root/.bitcoin
      - ./data/bitcoind:/root/.bitcoin/signet
    environment:
      UACOMMENT: $UACOMMENT
      BLOCKPRODUCTIONDELAY: $BLOCKPRODUCTIONDELAY
      NBITS: $NBITS
      RPCPASSWORD: $RPCPASSWORD
      SIGNETCHALLENGE: $SIGNETCHALLENGE
      EXTERNAL_IP: $EXTERNAL_IP
      MINERENABLED: $MINERENABLED
      ADDNODE: $ADDNODE
      RPCUSER: $RPCUSER
    ports:
      - "28332:28332"
      - "28333:28333"
      - "28334:28334"
      - "38332:38332"
      - "38333:38333"
      - "38334:38334"